/* AJA CARD REGISTER STRINGS STRUCTURE 
 * THIS FILE IS AUTOMATICALY GENERATED BY THE SPECTSOFT AJA-DRIVER PACKAGE */


#ifndef _AJA_REGSTRINGS_H_
#define _AJA_REGSTRINGS_H_


#include <aja_registers.h>

static const aja_regoption_t regopt_1080pdual[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_acapenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_acaplast[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_acapreset[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_acapwrapirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_acapwrapirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_acapwrapirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aes12invalid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aes34invalid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aes56invalid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aes78invalid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aessup[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ain12select[] = {
	{"aes", 0},
	{"sdi_g1c12", 1},
	{"sdi_g1c34", 2},
	{"sdi_g2c12", 3},
	{"sdi_g2c34", 4},
	{"sdi_g3c12", 5},
	{"sdi_g3c34", 6},
	{"sdi_g4c12", 7},
	{"sdi_g4c34", 8},
	{NULL, 0}
};

static const aja_regoption_t regopt_ain34select[] = {
	{"aes", 0},
	{"sdi_g1c12", 1},
	{"sdi_g1c34", 2},
	{"sdi_g2c12", 3},
	{"sdi_g2c34", 4},
	{"sdi_g3c12", 5},
	{"sdi_g3c34", 6},
	{"sdi_g4c12", 7},
	{"sdi_g4c34", 8},
	{NULL, 0}
};

static const aja_regoption_t regopt_ain56select[] = {
	{"aes", 0},
	{"sdi_g1c12", 1},
	{"sdi_g1c34", 2},
	{"sdi_g2c12", 3},
	{"sdi_g2c34", 4},
	{"sdi_g3c12", 5},
	{"sdi_g3c34", 6},
	{"sdi_g4c12", 7},
	{"sdi_g4c34", 8},
	{NULL, 0}
};

static const aja_regoption_t regopt_ain78select[] = {
	{"aes", 0},
	{"sdi_g1c12", 1},
	{"sdi_g1c34", 2},
	{"sdi_g2c12", 3},
	{"sdi_g2c34", 4},
	{"sdi_g3c12", 5},
	{"sdi_g3c34", 6},
	{"sdi_g4c12", 7},
	{"sdi_g4c34", 8},
	{NULL, 0}
};

static const aja_regoption_t regopt_amute12[] = {
	{"off", 0},
	{"on", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_amute34[] = {
	{"off", 0},
	{"on", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_amute56[] = {
	{"off", 0},
	{"on", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_amute78[] = {
	{"off", 0},
	{"on", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_aoutdac[] = {
	{"1080i_rgb", 9},
	{"1080i_rgb_vga", 15},
	{"1080i_ypbpr", 12},
	{"1080psf_rgb", 10},
	{"1080psf_rgb_vga", 16},
	{"1080psf_ypbpr", 13},
	{"480i_composite", 4},
	{"480i_composite_japan", 5},
	{"480i_rgb", 0},
	{"480i_ypbpb_betacam", 2},
	{"480i_ypbpr_japan", 3},
	{"480i_ypbpr_smpte", 1},
	{"576i_composite", 8},
	{"576i_rgb", 6},
	{"576i_ypbpr_smpte", 7},
	{"720p_rgb", 11},
	{"720p_rgb_vga", 17},
	{"720p_ypbpr", 14},
	{NULL, 0}
};

static const aja_regoption_t regopt_aoutxpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan1_ycbcr", 8},
	{"chan2_rgb", 0x8F},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"dlinput", 0x83},
	{"dlout", 0xB},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut1_ycbcr", 4},
	{"lut2_rgb", 0x8D},
	{"mix_ycbcr", 0x12},
	{"resconv", 6},
	{"sync1_rgb", 0x89},
	{"sync1_ycbcr", 9},
	{"sync2_rgb", 0x8A},
	{"sync2_ycbcr", 0xA},
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaylast[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaypause[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aplayreset[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaysize[] = {
	{"20bit", 1},
	{"24bit", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaywrapirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaywrapirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_aplaywrapirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_atoneoutput[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audio16chan[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audio8chan[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audio8chansup[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audio96khz[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audiobigbuffer[] = {
	{"1MB", 0},
	{"4MB", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audiocable[] = {
	{"bnc", 0},
	{"kbox", 1},
	{"xlr", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_audiocount[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audioirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audioirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audioirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audioloopback[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audioraw[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_audiowrapirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audiowrapirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_audiowrapirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_boardid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_boardversion[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_buserrorirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_buserrorirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_buserrorirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1alphainput2[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1dither[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1drtdisplay[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1extformat[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1flipvert[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1format[] = {
	{"argb8", 3},
	{"bgr8", 13},
	{"bgra8", 2},
	{"dpx_rgb10", 7},
	{"dpx_rgb10_le", 15},
	{"dpx_ycbcr10", 8},
	{"rgb10", 4},
	{"rgb8", 12},
	{"rgba8", 6},
	{"ycbcr10", 0},
	{"ycbcr8", 1},
	{"ycbcr8_dvcpro", 9},
	{"ycbcr8_hdv", 11},
	{"ycbcr8_qrez", 10},
	{"ycbcr8_rev", 5},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1framesize[] = {
	{"16mb", 3},
	{"2mb", 0},
	{"4mb", 1},
	{"8mb", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1input[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1lutcont[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1mode[] = {
	{"capture", 1},
	{"playback", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1output[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1pciframe[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rgbrange[] = {
	{"black@0x00", 0},
	{"black@0x40", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188_1[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188_2[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188dbb[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188dbb1[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188dbb2[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188filter[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188out[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188recv[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1rp188valid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1sfield[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1squeeze[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch1writeback[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2disable[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2dither[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2flipvert[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2format[] = {
	{"argb8", 3},
	{"bgr8", 13},
	{"bgra8", 2},
	{"dpx_rgb10", 7},
	{"dpx_rgb10_le", 15},
	{"dpx_ycbcr10", 8},
	{"rgb10", 4},
	{"rgb8", 12},
	{"rgba8", 6},
	{"ycbcr10", 0},
	{"ycbcr8", 1},
	{"ycbcr8_dvcpro", 9},
	{"ycbcr8_hdv", 11},
	{"ycbcr8_qrez", 10},
	{"ycbcr8_rev", 5},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2input[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2mode[] = {
	{"capture", 1},
	{"playback", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2output[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2pciframe[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188_1[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188_2[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188dbb[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188filter[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188out[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2rp188valid[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2sfield[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_ch2viper[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_chan1xpt[] = {
	{"black", 0},
	{"csconv1_rgb", 0x85},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"dlinput", 0x83},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut1_ycbcr", 4},
	{"lut2_rgb", 0x8D},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_chan2xpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"dlinput", 0x83},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut1_ycbcr", 4},
	{"lut2_rgb", 0x8D},
	{NULL, 0}
};

static const aja_regoption_t regopt_clutbank[] = {
	{"ch1bank0", 0},
	{"ch1bank1", 1},
	{"ch2bank0", 2},
	{"ch2bank1", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_compressxpt[] = {
	{"black", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1alphafromkey[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef0[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef1[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef2[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef3[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef4[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef5[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef6[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef7[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef8[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1coef9[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1customcoef[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1mode[] = {
	{"hd_coeff", 0},
	{"sd_coeff", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1rgbrange[] = {
	{"0x0-0x3FF", 0},
	{"0x40-0x3C0", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1syncfail[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv1xpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan1_ycbcr", 8},
	{"chan2_rgb", 0x8F},
	{"chan2_ycbcr", 0xF},
	{"dlinput", 0x83},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut2_rgb", 0x8D},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2alphafromkey[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef0[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef1[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef2[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef3[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef4[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef5[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef6[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef7[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef8[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2coef9[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2customcoef[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2keyxpt[] = {
	{"black", 0},
	{"input1", 1},
	{"input2", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2mode[] = {
	{"hd_coeff", 0},
	{"sd_coeff", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2rgbrange[] = {
	{"0x0-0x3FF", 0},
	{"0x40-0x3C0", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2syncfail[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_csconv2xpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan1_ycbcr", 8},
	{"chan2_rgb", 0x8F},
	{"chan2_ycbcr", 0xF},
	{"dlinput", 0x83},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut2_rgb", 0x8D},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconvkeyxpt[] = {
	{"black", 0},
	{"compress", 7},
	{"input1", 1},
	{"input2", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_csconvxpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan1_ycbcr", 8},
	{"chan2_rgb", 0x8F},
	{"chan2_ycbcr", 0xF},
	{"dlinput", 0x83},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut2_rgb", 0x8D},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_detect64bit[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dlinput[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_dloutput[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_dloutxpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan2_rgb", 0x8F},
	{"compress", 7},
	{"csconv1_rgb", 0x85},
	{"csconv2_rgb", 0x90},
	{"dlinput", 0x83},
	{"lut1_rgb", 0x84},
	{"lut2_rgb", 0x8D},
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1busy[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1cadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1count[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1go[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1hadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1hadd_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1next[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma1next_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2busy[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2cadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2count[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2go[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2hadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2hadd_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2next[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma2next_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3busy[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3cadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3count[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3go[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3hadd[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3hadd_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3next[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma3next_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4busy[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4go[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4hadd_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_dma4next_high[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_downconvmode[] = {
	{"anamorphic", 2},
	{"crop", 1},
	{"letterbox", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud1c12[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud1c34[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud1supress[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud2c12[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud2c34[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud2supress[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud3c12[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud3c34[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud4c12[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaud4c34[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_eaudselect[] = {
	{"input1", 0},
	{"input2", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_eaudsup[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_firmwarerev[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_force64bit[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_fpgaversion[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_framegeo[] = {
	{"1280x720", 1},
	{"1280x740", 9},
	{"1920x1080", 0},
	{"1920x1112", 8},
	{"2048x1080", 10},
	{"2048x1556", 11},
	{"720x486", 2},
	{"720x508", 6},
	{"720x576", 3},
	{"720x598", 7},
	{NULL, 0}
};

static const aja_regoption_t regopt_framerate[] = {
	{"23.976", 7},
	{"24", 6},
	{"25", 5},
	{"29.970", 4},
	{"30", 3},
	{"59.940", 2},
	{"60", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_framerate2k[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_horiztiming[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_inconvstd[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"1556i", 5},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_input1autotime[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1extframerate[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1extgeo[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1field[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1format[] = {
	{"1035", 7},
	{"1125", 4},
	{"1250", 5},
	{"525", 1},
	{"625", 2},
	{"750", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_input1framerate[] = {
	{"23.976", 7},
	{"24", 6},
	{"25", 5},
	{"29.970", 4},
	{"30", 3},
	{"59.940", 2},
	{"60", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_input1irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1prog[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input1vblank[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2autotime[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2extframerate[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2extgeo[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2field[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2format[] = {
	{"1035", 7},
	{"1125", 4},
	{"1250", 5},
	{"525", 1},
	{"625", 2},
	{"750", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_input2framerate[] = {
	{"23.976", 7},
	{"24", 6},
	{"25", 5},
	{"29.970", 4},
	{"30", 3},
	{"59.940", 2},
	{"60", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_input2irq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2irqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2irqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2prog[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_input2vblank[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_kboxinput[] = {
	{"bnc", 0},
	{"xlr", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_kboxmonitor[] = {
	{"ch12", 0},
	{"ch34", 1},
	{"ch56", 2},
	{"ch78", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_leds[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_lut1xpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan2_rgb", 0x8F},
	{"csconv1_rgb", 0x85},
	{"csconv2_rgb", 0x90},
	{"dlinput", 0x83},
	{NULL, 0}
};

static const aja_regoption_t regopt_lut2xpt[] = {
	{"black", 0},
	{"chan1_rgb", 0x88},
	{"chan2_rgb", 0x8F},
	{"csconv1_rgb", 0x85},
	{"csconv2_rgb", 0x90},
	{"dlinput", 0x83},
	{NULL, 0}
};

static const aja_regoption_t regopt_mattecb[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_mattecr[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_mattey[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_mixbgkeyxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1key_ycbcr", 0xE},
	{"csconv2_ycbcr", 0x10},
	{"csconv2key_ycbcr", 0x11},
	{"input1", 1},
	{"input2", 2},
	{"mixkey_ycbcr", 0x13},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_mixbgvidxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"input1", 1},
	{"input2", 2},
	{"mix_ycbcr", 0x12},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_mixer[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_mixfgkeyxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1key_ycbcr", 0xE},
	{"csconv2_ycbcr", 0x10},
	{"csconv2key_ycbcr", 0x11},
	{"input1", 1},
	{"input2", 2},
	{"mixkey_ycbcr", 0x13},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_mixfgvidxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"input1", 1},
	{"input2", 2},
	{"mix_ycbcr", 0x12},
	{"resconv", 6},
	{NULL, 0}
};

static const aja_regoption_t regopt_outconvstd[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"1556i", 5},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_outputfield[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_outputirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_outputirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_outputirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_outputline[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_outputvblank[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_panhoriz[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_panvert[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_panwindow[] = {
	{"1920x1080", 3},
	{"2048x1080", 2},
	{"disabled", 0},
	{"reserved", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_refformat[] = {
	{"1035", 7},
	{"1125", 4},
	{"1250", 5},
	{"525", 1},
	{"625", 2},
	{"750", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_refframerate[] = {
	{"23.976", 7},
	{"24", 6},
	{"25", 5},
	{"29.970", 4},
	{"30", 3},
	{"59.940", 2},
	{"60", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_refprog[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_refsource[] = {
	{"freerun", 3},
	{"input1", 1},
	{"input2", 2},
	{"refin", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_refvoltage[] = {
	{"1v", 0},
	{"4v", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_regclocking[] = {
	{"field", 0},
	{"frame", 1},
	{"immediate", 2},
	{"line10", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_resconv23[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_resconvsdanim[] = {
	{"hcrop", 1},
	{"letterbox", 0},
	{"pillarbox", 2},
	{"vcrop", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_resconvxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"csconv1_rgb", 0x85},
	{"csconv1_ycbcr", 5},
	{"csconv2_rgb", 0x90},
	{"csconv2_ycbcr", 0x10},
	{"input1", 1},
	{"input2", 2},
	{"lut1_rgb", 0x84},
	{"lut1_ycbcr", 4},
	{"lut2_rgb", 0x8D},
	{"sync1_ycbcr", 9},
	{"sync2_ycbcr", 0xA},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi1out2kline[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi1outhblankrgb[] = {
	{"black@0x00", 0},
	{"black@0x40", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi1outstd[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"1556i", 5},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi1outxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"compress", 7},
	{"csconv1_ycbcr", 5},
	{"csconv1key_ycbcr", 0xE},
	{"csconv2_ycbcr", 0x10},
	{"csconv2key_ycbcr", 0x11},
	{"dlout", 0xB},
	{"input1", 1},
	{"input2", 2},
	{"mix_ycbcr", 0x12},
	{"mixkey_ycbcr", 0x13},
	{"resconv", 6},
	{"sync1_ycbcr", 9},
	{"sync2_ycbcr", 0xA},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi2out2kline[] = {
	{"disabled", 0},
	{"enabled", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi2outhblankrgb[] = {
	{"black@0x00", 0},
	{"black@0x40", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi2outstd[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"1556i", 5},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_sdi2outxpt[] = {
	{"black", 0},
	{"chan1_ycbcr", 8},
	{"chan2_ycbcr", 0xF},
	{"compress", 7},
	{"csconv1_ycbcr", 5},
	{"csconv1key_ycbcr", 0xE},
	{"csconv2_ycbcr", 0x10},
	{"csconv2key_ycbcr", 0x11},
	{"dlout", 0xB},
	{"input1", 1},
	{"input2", 2},
	{"mix_ycbcr", 0x12},
	{"mixkey_ycbcr", 0x13},
	{"resconv", 6},
	{"sync1_ycbcr", 9},
	{"sync2_ycbcr", 0xA},
	{NULL, 0}
};

static const aja_regoption_t regopt_serialhigh[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_seriallow[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_splitslope[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_splitstart[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_splittype[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_standard[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_strapenabled[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartenablerx[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartenabletx[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartin[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartout[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartrxirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartrxirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartrxirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartrxoverrun[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartrxparityerror[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartstatusrx[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uartstatustx[] = {
	{"empty", 1},
	{"full", 2},
	{"hasdata", 0},
	{"undefined", 3},
	{NULL, 0}
};

static const aja_regoption_t regopt_uarttxirq[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uarttxirqclear[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_uarttxirqenable[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_upconvmode[] = {
	{"anamorphic", 0},
	{"pillarbox_4x3", 1},
	{"zoom_14x9", 2},
	{"zoom_letterbox", 3},
	{"zoom_wide", 4},
	{NULL, 0}
};

static const aja_regoption_t regopt_verttiming[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_data[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_done[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_pcix[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_program[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_ready[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vidfw_reset[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_viv[] = {
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_bgcont[] = {
	{"full", 0},
	{"shaped", 1},
	{"unshaped", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_fgcont[] = {
	{"full", 0},
	{"shaped", 1},
	{"unshaped", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_limiting[] = {
	{"broadcast", 2},
	{"illegal", 1},
	{"legalsdi", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mode[] = {
	{"fgoff", 3},
	{"fgon", 0},
	{"mix", 1},
	{"split", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mux1[] = {
	{"fgv", 1},
	{"zero", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mux2[] = {
	{"fkey", 0},
	{"mix", 1},
	{"split", 2},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mux3[] = {
	{"fgv", 1},
	{"zero", 0},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mux4[] = {
	{"bgv", 0},
	{"bgvxbgkey", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_mux5[] = {
	{"bgkey", 3},
	{"bgv", 0},
	{"fgkey", 2},
	{"fgv", 1},
	{"keymix", 4},
	{"secv", 5},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_standard[] = {
	{"1080i", 0},
	{"1080p", 4},
	{"1556i", 5},
	{"480i", 2},
	{"576i", 3},
	{"720p", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpc_syncfail[] = {
	{"insync", 0},
	{"outofsync", 1},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpcc_bgkey[] = {
	{"chan1key", 0},
	{"chan2key", 1},
	{"input1", 2},
	{"input2", 3},
	{"matte", 4},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpcc_bgv[] = {
	{"chan1", 0},
	{"chan1key", 5},
	{"chan2", 1},
	{"chan2key", 6},
	{"input1", 2},
	{"input2", 3},
	{"matte", 4},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpcc_fgkey[] = {
	{"chan1key", 0},
	{"chan2key", 1},
	{"input1", 2},
	{"input2", 3},
	{"matte", 4},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpcc_fgv[] = {
	{"chan1", 0},
	{"chan1key", 5},
	{"chan2", 1},
	{"chan2key", 6},
	{"input1", 2},
	{"input2", 3},
	{"matte", 4},
	{NULL, 0}
};

static const aja_regoption_t regopt_vpcc_secv[] = {
	{"chan1key", 0},
	{"chan2key", 1},
	{"input1", 2},
	{"input2", 3},
	{"matte", 4},
	{NULL, 0}
};

static const aja_regstring_t regstring[] = {
	{"1080pdual", "1080p50/60 dual link output enable", (const aja_register_t *)&ajareg_1080pdual, (const aja_regoption_t *)&regopt_1080pdual, 0x7},
	{"acapenable", "Audio Capture Enable", (const aja_register_t *)&ajareg_acapenable, (const aja_regoption_t *)&regopt_acapenable, 0x3},
	{"acaplast", "Audio Capture Last Address", (const aja_register_t *)&ajareg_acaplast, (const aja_regoption_t *)&regopt_acaplast, 0x1},
	{"acapreset", "Audio Capture Reset", (const aja_register_t *)&ajareg_acapreset, (const aja_regoption_t *)&regopt_acapreset, 0x3},
	{"acapwrapirq", "Audio Capture Wrap IRQ Active (depreciated)", (const aja_register_t *)&ajareg_acapwrapirq, (const aja_regoption_t *)&regopt_acapwrapirq, 0x1},
	{"acapwrapirqclear", "Audio Capture Wrap IRQ Clear (depreciated)", (const aja_register_t *)&ajareg_acapwrapirqclear, (const aja_regoption_t *)&regopt_acapwrapirqclear, 0x2},
	{"acapwrapirqenable", "Audio Capture Wrap IRQ Enable (depreciated)", (const aja_register_t *)&ajareg_acapwrapirqenable, (const aja_regoption_t *)&regopt_acapwrapirqenable, 0x3},
	{"aes12invalid", "AES 1/2 Invalid Data", (const aja_register_t *)&ajareg_aes12invalid, (const aja_regoption_t *)&regopt_aes12invalid, 0x1},
	{"aes34invalid", "AES 3/4 Invalid Data", (const aja_register_t *)&ajareg_aes34invalid, (const aja_regoption_t *)&regopt_aes34invalid, 0x1},
	{"aes56invalid", "AES 5/6 Invalid Data", (const aja_register_t *)&ajareg_aes56invalid, (const aja_regoption_t *)&regopt_aes56invalid, 0x1},
	{"aes78invalid", "AES 7/8 Invalid Data", (const aja_register_t *)&ajareg_aes78invalid, (const aja_regoption_t *)&regopt_aes78invalid, 0x1},
	{"aessup", "AES/EBU Supported", (const aja_register_t *)&ajareg_aessup, (const aja_regoption_t *)&regopt_aessup, 0x1},
	{"ain12select", "Audio Buffer 1/2 Select", (const aja_register_t *)&ajareg_ain12select, (const aja_regoption_t *)&regopt_ain12select, 0x7},
	{"ain34select", "Audio Buffer 3/4 Select", (const aja_register_t *)&ajareg_ain34select, (const aja_regoption_t *)&regopt_ain34select, 0x7},
	{"ain56select", "Audio Buffer 5/6 Select", (const aja_register_t *)&ajareg_ain56select, (const aja_regoption_t *)&regopt_ain56select, 0x7},
	{"ain78select", "Audio Buffer 7/8 Select", (const aja_register_t *)&ajareg_ain78select, (const aja_regoption_t *)&regopt_ain78select, 0x7},
	{"amute12", "Audio Mute Ch 1/2", (const aja_register_t *)&ajareg_amute12, (const aja_regoption_t *)&regopt_amute12, 0x7},
	{"amute34", "Audio Mute Ch 3/4", (const aja_register_t *)&ajareg_amute34, (const aja_regoption_t *)&regopt_amute34, 0x7},
	{"amute56", "Audio Mute Ch 5/6", (const aja_register_t *)&ajareg_amute56, (const aja_regoption_t *)&regopt_amute56, 0x7},
	{"amute78", "Audio Mute Ch 7/8", (const aja_register_t *)&ajareg_amute78, (const aja_regoption_t *)&regopt_amute78, 0x7},
	{"aoutdac", "Analog Out - DAC Mode", (const aja_register_t *)&ajareg_aoutdac, (const aja_regoption_t *)&regopt_aoutdac, 0x7},
	{"aoutxpt", "Analog Out Crosspoint", (const aja_register_t *)&ajareg_aoutxpt, (const aja_regoption_t *)&regopt_aoutxpt, 0x7},
	{"aplaylast", "Audio Playback Last Address", (const aja_register_t *)&ajareg_aplaylast, (const aja_regoption_t *)&regopt_aplaylast, 0x1},
	{"aplaypause", "Audio Playback Pause", (const aja_register_t *)&ajareg_aplaypause, (const aja_regoption_t *)&regopt_aplaypause, 0x3},
	{"aplayreset", "Audio Playback Reset", (const aja_register_t *)&ajareg_aplayreset, (const aja_regoption_t *)&regopt_aplayreset, 0x3},
	{"aplaysize", "Audio 20bit Output", (const aja_register_t *)&ajareg_aplaysize, (const aja_regoption_t *)&regopt_aplaysize, 0x7},
	{"aplaywrapirq", "Audio Playback Wrap IRQ Active (depreciated)", (const aja_register_t *)&ajareg_aplaywrapirq, (const aja_regoption_t *)&regopt_aplaywrapirq, 0x1},
	{"aplaywrapirqclear", "Audio Playback Wrap IRQ Clear (depreciated)", (const aja_register_t *)&ajareg_aplaywrapirqclear, (const aja_regoption_t *)&regopt_aplaywrapirqclear, 0x2},
	{"aplaywrapirqenable", "Audio Playback Wrap IRQ Enable (depreciated)", (const aja_register_t *)&ajareg_aplaywrapirqenable, (const aja_regoption_t *)&regopt_aplaywrapirqenable, 0x3},
	{"atoneoutput", "Audio Tone Output Enable", (const aja_register_t *)&ajareg_atoneoutput, (const aja_regoption_t *)&regopt_atoneoutput, 0x7},
	{"audio16chan", "Enable 16 channels of audio", (const aja_register_t *)&ajareg_audio16chan, (const aja_regoption_t *)&regopt_audio16chan, 0x7},
	{"audio8chan", "Enable 8 channels of audio", (const aja_register_t *)&ajareg_audio8chan, (const aja_regoption_t *)&regopt_audio8chan, 0x7},
	{"audio8chansup", "8 Channel Audio Supported", (const aja_register_t *)&ajareg_audio8chansup, (const aja_regoption_t *)&regopt_audio8chansup, 0x1},
	{"audio96khz", "Enable 96KHz audio sample rate", (const aja_register_t *)&ajareg_audio96khz, (const aja_regoption_t *)&regopt_audio96khz, 0x7},
	{"audiobigbuffer", "Audio Buffer Size", (const aja_register_t *)&ajareg_audiobigbuffer, (const aja_regoption_t *)&regopt_audiobigbuffer, 0x7},
	{"audiocable", "Audio Cable Type", (const aja_register_t *)&ajareg_audiocable, (const aja_regoption_t *)&regopt_audiocable, 0x1},
	{"audiocount", "48KHz Audio Counter", (const aja_register_t *)&ajareg_audiocount, (const aja_regoption_t *)&regopt_audiocount, 0x1},
	{"audioirq", "Audio 50Hz IRQ Active (depreciated)", (const aja_register_t *)&ajareg_audioirq, (const aja_regoption_t *)&regopt_audioirq, 0x1},
	{"audioirqclear", "Audio 50Hz IRQ Clear (depreciated)", (const aja_register_t *)&ajareg_audioirqclear, (const aja_regoption_t *)&regopt_audioirqclear, 0x2},
	{"audioirqenable", "Audio 50Hz IRQ Enable (depreciated)", (const aja_register_t *)&ajareg_audioirqenable, (const aja_regoption_t *)&regopt_audioirqenable, 0x3},
	{"audioloopback", "Audio Loopback Enable", (const aja_register_t *)&ajareg_audioloopback, (const aja_regoption_t *)&regopt_audioloopback, 0x7},
	{"audioraw", "Enable raw AES/EBU recording from ch1&2", (const aja_register_t *)&ajareg_audioraw, (const aja_regoption_t *)&regopt_audioraw, 0x7},
	{"audiowrapirq", "Audio Wrap IRQ Active", (const aja_register_t *)&ajareg_audiowrapirq, (const aja_regoption_t *)&regopt_audiowrapirq, 0x1},
	{"audiowrapirqclear", "Audio Wrap IRQ Clear", (const aja_register_t *)&ajareg_audiowrapirqclear, (const aja_regoption_t *)&regopt_audiowrapirqclear, 0x2},
	{"audiowrapirqenable", "Audio Wrap IRQ Enable", (const aja_register_t *)&ajareg_audiowrapirqenable, (const aja_regoption_t *)&regopt_audiowrapirqenable, 0x3},
	{"boardid", "Board ID", (const aja_register_t *)&ajareg_boardid, (const aja_regoption_t *)&regopt_boardid, 0x1},
	{"boardversion", "Board Version Number", (const aja_register_t *)&ajareg_boardversion, (const aja_regoption_t *)&regopt_boardversion, 0x1},
	{"buserrorirq", "Bus Error IRQ Active", (const aja_register_t *)&ajareg_buserrorirq, (const aja_regoption_t *)&regopt_buserrorirq, 0x1},
	{"buserrorirqclear", "Clear Bus Error IRQ Error", (const aja_register_t *)&ajareg_buserrorirqclear, (const aja_regoption_t *)&regopt_buserrorirqclear, 0x2},
	{"buserrorirqenable", "Bus Error IRQ Enable", (const aja_register_t *)&ajareg_buserrorirqenable, (const aja_regoption_t *)&regopt_buserrorirqenable, 0x3},
	{"ch1alphainput2", "Chan 1 Alpha from Input 2", (const aja_register_t *)&ajareg_ch1alphainput2, (const aja_regoption_t *)&regopt_ch1alphainput2, 0x7},
	{"ch1dither", "Chan 1 Dither Input", (const aja_register_t *)&ajareg_ch1dither, (const aja_regoption_t *)&regopt_ch1dither, 0x7},
	{"ch1drtdisplay", "DRT Display?", (const aja_register_t *)&ajareg_ch1drtdisplay, (const aja_regoption_t *)&regopt_ch1drtdisplay, 0x7},
	{"ch1extformat", "Chan 1 extended format", (const aja_register_t *)&ajareg_ch1extformat, (const aja_regoption_t *)&regopt_ch1extformat, 0x7},
	{"ch1flipvert", "Chan 1 Flip Vertical", (const aja_register_t *)&ajareg_ch1flipvert, (const aja_regoption_t *)&regopt_ch1flipvert, 0x7},
	{"ch1format", "Chan 1 Format", (const aja_register_t *)&ajareg_ch1format, (const aja_regoption_t *)&regopt_ch1format, 0x7},
	{"ch1framesize", "Chan 1 Frame Size", (const aja_register_t *)&ajareg_ch1framesize, (const aja_regoption_t *)&regopt_ch1framesize, 0x1},
	{"ch1input", "Chan 1 Input Frame", (const aja_register_t *)&ajareg_ch1input, (const aja_regoption_t *)&regopt_ch1input, 0x3},
	{"ch1lutcont", "Chan 1 LUT Control", (const aja_register_t *)&ajareg_ch1lutcont, (const aja_regoption_t *)&regopt_ch1lutcont, 0x3},
	{"ch1mode", "Chan 1 Mode", (const aja_register_t *)&ajareg_ch1mode, (const aja_regoption_t *)&regopt_ch1mode, 0x7},
	{"ch1output", "Chan 1 Output Frame", (const aja_register_t *)&ajareg_ch1output, (const aja_regoption_t *)&regopt_ch1output, 0x3},
	{"ch1pciframe", "Chan 1 PCI Frame", (const aja_register_t *)&ajareg_ch1pciframe, (const aja_regoption_t *)&regopt_ch1pciframe, 0x3},
	{"ch1rgbrange", "RGB Range", (const aja_register_t *)&ajareg_ch1rgbrange, (const aja_regoption_t *)&regopt_ch1rgbrange, 0x7},
	{"ch1rp188_1", "Chan 1 RP188 Bits 0-31", (const aja_register_t *)&ajareg_ch1rp188_1, (const aja_regoption_t *)&regopt_ch1rp188_1, 0x3},
	{"ch1rp188_2", "Chan 1 RP188 Bits 32-63", (const aja_register_t *)&ajareg_ch1rp188_2, (const aja_regoption_t *)&regopt_ch1rp188_2, 0x3},
	{"ch1rp188dbb", "Chan 1 RP188 DBB", (const aja_register_t *)&ajareg_ch1rp188dbb, (const aja_regoption_t *)&regopt_ch1rp188dbb, 0x3},
	{"ch1rp188dbb1", "Chan 1 RP188 DBB 1", (const aja_register_t *)&ajareg_ch1rp188dbb1, (const aja_regoption_t *)&regopt_ch1rp188dbb1, 0x3},
	{"ch1rp188dbb2", "Chan 1 RP188 DBB 2", (const aja_register_t *)&ajareg_ch1rp188dbb2, (const aja_regoption_t *)&regopt_ch1rp188dbb2, 0x3},
	{"ch1rp188filter", "Chan 1 RP188 filter", (const aja_register_t *)&ajareg_ch1rp188filter, (const aja_regoption_t *)&regopt_ch1rp188filter, 0x3},
	{"ch1rp188out", "Chan 1 RP-188 Output", (const aja_register_t *)&ajareg_ch1rp188out, (const aja_regoption_t *)&regopt_ch1rp188out, 0x7},
	{"ch1rp188recv", "Chan 1 RP188 recieved", (const aja_register_t *)&ajareg_ch1rp188recv, (const aja_regoption_t *)&regopt_ch1rp188recv, 0x1},
	{"ch1rp188valid", "Chan 1 RP188 recieved valid", (const aja_register_t *)&ajareg_ch1rp188valid, (const aja_regoption_t *)&regopt_ch1rp188valid, 0x1},
	{"ch1sfield", "Chan 1 Single Field", (const aja_register_t *)&ajareg_ch1sfield, (const aja_regoption_t *)&regopt_ch1sfield, 0x7},
	{"ch1squeeze", "Chan 1 Horizontal Squeeze", (const aja_register_t *)&ajareg_ch1squeeze, (const aja_regoption_t *)&regopt_ch1squeeze, 0x7},
	{"ch1writeback", "Chan 1 Writeback", (const aja_register_t *)&ajareg_ch1writeback, (const aja_regoption_t *)&regopt_ch1writeback, 0x7},
	{"ch2disable", "Chan 2 Disable", (const aja_register_t *)&ajareg_ch2disable, (const aja_regoption_t *)&regopt_ch2disable, 0x7},
	{"ch2dither", "Chan 2 Dither Input", (const aja_register_t *)&ajareg_ch2dither, (const aja_regoption_t *)&regopt_ch2dither, 0x7},
	{"ch2flipvert", "Chan 2 Flip Vertical", (const aja_register_t *)&ajareg_ch2flipvert, (const aja_regoption_t *)&regopt_ch2flipvert, 0x7},
	{"ch2format", "Chan 2 Format", (const aja_register_t *)&ajareg_ch2format, (const aja_regoption_t *)&regopt_ch2format, 0x7},
	{"ch2input", "Chan 2 Input Frame", (const aja_register_t *)&ajareg_ch2input, (const aja_regoption_t *)&regopt_ch2input, 0x3},
	{"ch2mode", "Chan 2 Mode", (const aja_register_t *)&ajareg_ch2mode, (const aja_regoption_t *)&regopt_ch2mode, 0x7},
	{"ch2output", "Chan 2 Output Frame", (const aja_register_t *)&ajareg_ch2output, (const aja_regoption_t *)&regopt_ch2output, 0x3},
	{"ch2pciframe", "Chan 2 PCI Frame", (const aja_register_t *)&ajareg_ch2pciframe, (const aja_regoption_t *)&regopt_ch2pciframe, 0x3},
	{"ch2rp188_1", "Input/Output 2 RP188 low", (const aja_register_t *)&ajareg_ch2rp188_1, (const aja_regoption_t *)&regopt_ch2rp188_1, 0x3},
	{"ch2rp188_2", "Input/Output 2 RP188 high", (const aja_register_t *)&ajareg_ch2rp188_2, (const aja_regoption_t *)&regopt_ch2rp188_2, 0x3},
	{"ch2rp188dbb", "Input/Output 2 RP188 DBB", (const aja_register_t *)&ajareg_ch2rp188dbb, (const aja_regoption_t *)&regopt_ch2rp188dbb, 0x3},
	{"ch2rp188filter", "Channel 2 RP188 filter", (const aja_register_t *)&ajareg_ch2rp188filter, (const aja_regoption_t *)&regopt_ch2rp188filter, 0x3},
	{"ch2rp188out", "Chan 2 RP-188 Output", (const aja_register_t *)&ajareg_ch2rp188out, (const aja_regoption_t *)&regopt_ch2rp188out, 0x7},
	{"ch2rp188valid", "Input 2 RP188 Valid", (const aja_register_t *)&ajareg_ch2rp188valid, (const aja_regoption_t *)&regopt_ch2rp188valid, 0x1},
	{"ch2sfield", "Chan 2 Single Field", (const aja_register_t *)&ajareg_ch2sfield, (const aja_regoption_t *)&regopt_ch2sfield, 0x7},
	{"ch2viper", "Chan 2 Viper Squeeze", (const aja_register_t *)&ajareg_ch2viper, (const aja_regoption_t *)&regopt_ch2viper, 0x7},
	{"chan1xpt", "Channel 1 Crosspoint", (const aja_register_t *)&ajareg_chan1xpt, (const aja_regoption_t *)&regopt_chan1xpt, 0x7},
	{"chan2xpt", "FrameBuffer 2 Crosspoint", (const aja_register_t *)&ajareg_chan2xpt, (const aja_regoption_t *)&regopt_chan2xpt, 0x7},
	{"clutbank", "Color Correction Bank Select", (const aja_register_t *)&ajareg_clutbank, (const aja_regoption_t *)&regopt_clutbank, 0x7},
	{"compressxpt", "Compressor Crosspoint", (const aja_register_t *)&ajareg_compressxpt, (const aja_regoption_t *)&regopt_compressxpt, 0x7},
	{"csconv1alphafromkey", "Colorspace Converter 1 make alpha from key", (const aja_register_t *)&ajareg_csconv1alphafromkey, (const aja_regoption_t *)&regopt_csconv1alphafromkey, 0x7},
	{"csconv1coef0", "Colorspace Converter 1 Custom Coefficient 0", (const aja_register_t *)&ajareg_csconv1coef0, (const aja_regoption_t *)&regopt_csconv1coef0, 0x7},
	{"csconv1coef1", "Colorspace Converter 1 Custom Coefficient 1", (const aja_register_t *)&ajareg_csconv1coef1, (const aja_regoption_t *)&regopt_csconv1coef1, 0x7},
	{"csconv1coef2", "Colorspace Converter 1 Custom Coefficient 2", (const aja_register_t *)&ajareg_csconv1coef2, (const aja_regoption_t *)&regopt_csconv1coef2, 0x7},
	{"csconv1coef3", "Colorspace Converter 1 Custom Coefficient 3", (const aja_register_t *)&ajareg_csconv1coef3, (const aja_regoption_t *)&regopt_csconv1coef3, 0x7},
	{"csconv1coef4", "Colorspace Converter 1 Custom Coefficient 4", (const aja_register_t *)&ajareg_csconv1coef4, (const aja_regoption_t *)&regopt_csconv1coef4, 0x7},
	{"csconv1coef5", "Colorspace Converter 1 Custom Coefficient 5", (const aja_register_t *)&ajareg_csconv1coef5, (const aja_regoption_t *)&regopt_csconv1coef5, 0x7},
	{"csconv1coef6", "Colorspace Converter 1 Custom Coefficient 6", (const aja_register_t *)&ajareg_csconv1coef6, (const aja_regoption_t *)&regopt_csconv1coef6, 0x7},
	{"csconv1coef7", "Colorspace Converter 1 Custom Coefficient 7", (const aja_register_t *)&ajareg_csconv1coef7, (const aja_regoption_t *)&regopt_csconv1coef7, 0x7},
	{"csconv1coef8", "Colorspace Converter 1 Custom Coefficient 8", (const aja_register_t *)&ajareg_csconv1coef8, (const aja_regoption_t *)&regopt_csconv1coef8, 0x7},
	{"csconv1coef9", "Colorspace Converter 1 Custom Coefficient 9", (const aja_register_t *)&ajareg_csconv1coef9, (const aja_regoption_t *)&regopt_csconv1coef9, 0x7},
	{"csconv1customcoef", "Colorspace Converter 1 use custom coefficents", (const aja_register_t *)&ajareg_csconv1customcoef, (const aja_regoption_t *)&regopt_csconv1customcoef, 0x7},
	{"csconv1mode", "Colorspace Converter 1 Coefficient", (const aja_register_t *)&ajareg_csconv1mode, (const aja_regoption_t *)&regopt_csconv1mode, 0x7},
	{"csconv1rgbrange", "Colorspace Converter 1 RGB range", (const aja_register_t *)&ajareg_csconv1rgbrange, (const aja_regoption_t *)&regopt_csconv1rgbrange, 0x7},
	{"csconv1syncfail", "Colorspace Converter 1 sync fail", (const aja_register_t *)&ajareg_csconv1syncfail, (const aja_regoption_t *)&regopt_csconv1syncfail, 0x1},
	{"csconv1xpt", "Colorspace Converter 1 Crosspoint", (const aja_register_t *)&ajareg_csconv1xpt, (const aja_regoption_t *)&regopt_csconv1xpt, 0x7},
	{"csconv2alphafromkey", "Colorspace Converter 2 make alpha from key", (const aja_register_t *)&ajareg_csconv2alphafromkey, (const aja_regoption_t *)&regopt_csconv2alphafromkey, 0x7},
	{"csconv2coef0", "Colorspace Converter 2 Custom Coefficient 0", (const aja_register_t *)&ajareg_csconv2coef0, (const aja_regoption_t *)&regopt_csconv2coef0, 0x7},
	{"csconv2coef1", "Colorspace Converter 2 Custom Coefficient 1", (const aja_register_t *)&ajareg_csconv2coef1, (const aja_regoption_t *)&regopt_csconv2coef1, 0x7},
	{"csconv2coef2", "Colorspace Converter 2 Custom Coefficient 2", (const aja_register_t *)&ajareg_csconv2coef2, (const aja_regoption_t *)&regopt_csconv2coef2, 0x7},
	{"csconv2coef3", "Colorspace Converter 2 Custom Coefficient 3", (const aja_register_t *)&ajareg_csconv2coef3, (const aja_regoption_t *)&regopt_csconv2coef3, 0x7},
	{"csconv2coef4", "Colorspace Converter 2 Custom Coefficient 4", (const aja_register_t *)&ajareg_csconv2coef4, (const aja_regoption_t *)&regopt_csconv2coef4, 0x7},
	{"csconv2coef5", "Colorspace Converter 2 Custom Coefficient 5", (const aja_register_t *)&ajareg_csconv2coef5, (const aja_regoption_t *)&regopt_csconv2coef5, 0x7},
	{"csconv2coef6", "Colorspace Converter 2 Custom Coefficient 6", (const aja_register_t *)&ajareg_csconv2coef6, (const aja_regoption_t *)&regopt_csconv2coef6, 0x7},
	{"csconv2coef7", "Colorspace Converter 2 Custom Coefficient 7", (const aja_register_t *)&ajareg_csconv2coef7, (const aja_regoption_t *)&regopt_csconv2coef7, 0x7},
	{"csconv2coef8", "Colorspace Converter 2 Custom Coefficient 8", (const aja_register_t *)&ajareg_csconv2coef8, (const aja_regoption_t *)&regopt_csconv2coef8, 0x7},
	{"csconv2coef9", "Colorspace Converter 2 Custom Coefficient 9", (const aja_register_t *)&ajareg_csconv2coef9, (const aja_regoption_t *)&regopt_csconv2coef9, 0x7},
	{"csconv2customcoef", "Colorspace Converter 2 use custom coefficents", (const aja_register_t *)&ajareg_csconv2customcoef, (const aja_regoption_t *)&regopt_csconv2customcoef, 0x7},
	{"csconv2keyxpt", "ColorSpace Converter 2 Key Crosspoint", (const aja_register_t *)&ajareg_csconv2keyxpt, (const aja_regoption_t *)&regopt_csconv2keyxpt, 0x7},
	{"csconv2mode", "Colorspace Converter 2 Coefficient", (const aja_register_t *)&ajareg_csconv2mode, (const aja_regoption_t *)&regopt_csconv2mode, 0x7},
	{"csconv2rgbrange", "Colorspace Converter 2 RGB range", (const aja_register_t *)&ajareg_csconv2rgbrange, (const aja_regoption_t *)&regopt_csconv2rgbrange, 0x7},
	{"csconv2syncfail", "Colorspace Converter 2 sync fail", (const aja_register_t *)&ajareg_csconv2syncfail, (const aja_regoption_t *)&regopt_csconv2syncfail, 0x1},
	{"csconv2xpt", "Colorspace Converter 2 Crosspoint", (const aja_register_t *)&ajareg_csconv2xpt, (const aja_regoption_t *)&regopt_csconv2xpt, 0x7},
	{"csconvkeyxpt", "ColorSpace Converter Key Crosspoint", (const aja_register_t *)&ajareg_csconvkeyxpt, (const aja_regoption_t *)&regopt_csconvkeyxpt, 0x7},
	{"csconvxpt", "Colorspace Converter 1 Crosspoint", (const aja_register_t *)&ajareg_csconvxpt, (const aja_regoption_t *)&regopt_csconvxpt, 0x7},
	{"detect64bit", "Detect 64bit PCI", (const aja_register_t *)&ajareg_detect64bit, (const aja_regoption_t *)&regopt_detect64bit, 0x1},
	{"dlinput", "Enable Dual Link Input", (const aja_register_t *)&ajareg_dlinput, (const aja_regoption_t *)&regopt_dlinput, 0x7},
	{"dloutput", "Enable Dual Link Output", (const aja_register_t *)&ajareg_dloutput, (const aja_regoption_t *)&regopt_dloutput, 0x7},
	{"dloutxpt", "Dual-Link Output Crosspoint", (const aja_register_t *)&ajareg_dloutxpt, (const aja_regoption_t *)&regopt_dloutxpt, 0x7},
	{"dma1busy", "DMA 1 Busy", (const aja_register_t *)&ajareg_dma1busy, (const aja_regoption_t *)&regopt_dma1busy, 0x1},
	{"dma1cadd", "DMA 1 Card Address", (const aja_register_t *)&ajareg_dma1cadd, (const aja_regoption_t *)&regopt_dma1cadd, 0x3},
	{"dma1count", "DMA 1 Word Count", (const aja_register_t *)&ajareg_dma1count, (const aja_regoption_t *)&regopt_dma1count, 0x3},
	{"dma1go", "DMA 1 GO", (const aja_register_t *)&ajareg_dma1go, (const aja_regoption_t *)&regopt_dma1go, 0x2},
	{"dma1hadd", "DMA 1 Host Address", (const aja_register_t *)&ajareg_dma1hadd, (const aja_regoption_t *)&regopt_dma1hadd, 0x3},
	{"dma1hadd_high", "DMA 1 Host Address (MSB 32)", (const aja_register_t *)&ajareg_dma1hadd_high, (const aja_regoption_t *)&regopt_dma1hadd_high, 0x3},
	{"dma1irq", "DMA 1 IRQ Active", (const aja_register_t *)&ajareg_dma1irq, (const aja_regoption_t *)&regopt_dma1irq, 0x1},
	{"dma1irqclear", "Clear DMA 1 IRQ", (const aja_register_t *)&ajareg_dma1irqclear, (const aja_regoption_t *)&regopt_dma1irqclear, 0x2},
	{"dma1irqenable", "DMA 1 IRQ Enable", (const aja_register_t *)&ajareg_dma1irqenable, (const aja_regoption_t *)&regopt_dma1irqenable, 0x3},
	{"dma1next", "DMA 1 Next Descriptor", (const aja_register_t *)&ajareg_dma1next, (const aja_regoption_t *)&regopt_dma1next, 0x3},
	{"dma1next_high", "DMA 1 Next Descriptor Address (MSB 32)", (const aja_register_t *)&ajareg_dma1next_high, (const aja_regoption_t *)&regopt_dma1next_high, 0x3},
	{"dma2busy", "DMA 2 Busy", (const aja_register_t *)&ajareg_dma2busy, (const aja_regoption_t *)&regopt_dma2busy, 0x1},
	{"dma2cadd", "DMA 2 Card Address", (const aja_register_t *)&ajareg_dma2cadd, (const aja_regoption_t *)&regopt_dma2cadd, 0x3},
	{"dma2count", "DMA 2 Word Count", (const aja_register_t *)&ajareg_dma2count, (const aja_regoption_t *)&regopt_dma2count, 0x3},
	{"dma2go", "DMA 2 GO", (const aja_register_t *)&ajareg_dma2go, (const aja_regoption_t *)&regopt_dma2go, 0x2},
	{"dma2hadd", "DMA 2 Host Address", (const aja_register_t *)&ajareg_dma2hadd, (const aja_regoption_t *)&regopt_dma2hadd, 0x3},
	{"dma2hadd_high", "DMA 1 Host Address (MSB 32)", (const aja_register_t *)&ajareg_dma2hadd_high, (const aja_regoption_t *)&regopt_dma2hadd_high, 0x3},
	{"dma2irq", "DMA 2 IRQ Active", (const aja_register_t *)&ajareg_dma2irq, (const aja_regoption_t *)&regopt_dma2irq, 0x1},
	{"dma2irqclear", "Clear DMA 2 IRQ", (const aja_register_t *)&ajareg_dma2irqclear, (const aja_regoption_t *)&regopt_dma2irqclear, 0x2},
	{"dma2irqenable", "DMA 2 IRQ Enable", (const aja_register_t *)&ajareg_dma2irqenable, (const aja_regoption_t *)&regopt_dma2irqenable, 0x3},
	{"dma2next", "DMA 2 Next Descriptor", (const aja_register_t *)&ajareg_dma2next, (const aja_regoption_t *)&regopt_dma2next, 0x3},
	{"dma2next_high", "DMA 1 Next Descriptor Address (MSB 32)", (const aja_register_t *)&ajareg_dma2next_high, (const aja_regoption_t *)&regopt_dma2next_high, 0x3},
	{"dma3busy", "DMA 3 Busy", (const aja_register_t *)&ajareg_dma3busy, (const aja_regoption_t *)&regopt_dma3busy, 0x1},
	{"dma3cadd", "DMA 3 Card Address", (const aja_register_t *)&ajareg_dma3cadd, (const aja_regoption_t *)&regopt_dma3cadd, 0x3},
	{"dma3count", "DMA 3 Word Count", (const aja_register_t *)&ajareg_dma3count, (const aja_regoption_t *)&regopt_dma3count, 0x3},
	{"dma3go", "DMA 3 GO", (const aja_register_t *)&ajareg_dma3go, (const aja_regoption_t *)&regopt_dma3go, 0x2},
	{"dma3hadd", "DMA 3 Host Address", (const aja_register_t *)&ajareg_dma3hadd, (const aja_regoption_t *)&regopt_dma3hadd, 0x3},
	{"dma3hadd_high", "DMA 1 Host Address (MSB 32)", (const aja_register_t *)&ajareg_dma3hadd_high, (const aja_regoption_t *)&regopt_dma3hadd_high, 0x3},
	{"dma3irq", "DMA 3 IRQ Active", (const aja_register_t *)&ajareg_dma3irq, (const aja_regoption_t *)&regopt_dma3irq, 0x1},
	{"dma3irqclear", "Clear DMA 3 IRQ", (const aja_register_t *)&ajareg_dma3irqclear, (const aja_regoption_t *)&regopt_dma3irqclear, 0x2},
	{"dma3irqenable", "DMA 3 IRQ Enable", (const aja_register_t *)&ajareg_dma3irqenable, (const aja_regoption_t *)&regopt_dma3irqenable, 0x3},
	{"dma3next", "DMA 3 Next Descriptor", (const aja_register_t *)&ajareg_dma3next, (const aja_regoption_t *)&regopt_dma3next, 0x3},
	{"dma3next_high", "DMA 1 Next Descriptor Address (MSB 32)", (const aja_register_t *)&ajareg_dma3next_high, (const aja_regoption_t *)&regopt_dma3next_high, 0x3},
	{"dma4busy", "DMA 4 Busy", (const aja_register_t *)&ajareg_dma4busy, (const aja_regoption_t *)&regopt_dma4busy, 0x1},
	{"dma4go", "DMA 4 GO", (const aja_register_t *)&ajareg_dma4go, (const aja_regoption_t *)&regopt_dma4go, 0x2},
	{"dma4hadd_high", "DMA 1 Host Address (MSB 32)", (const aja_register_t *)&ajareg_dma4hadd_high, (const aja_regoption_t *)&regopt_dma4hadd_high, 0x3},
	{"dma4irq", "DMA 4 IRQ Active", (const aja_register_t *)&ajareg_dma4irq, (const aja_regoption_t *)&regopt_dma4irq, 0x1},
	{"dma4irqclear", "Clear DMA 4 IRQ", (const aja_register_t *)&ajareg_dma4irqclear, (const aja_regoption_t *)&regopt_dma4irqclear, 0x2},
	{"dma4irqenable", "DMA 4 IRQ Enable", (const aja_register_t *)&ajareg_dma4irqenable, (const aja_regoption_t *)&regopt_dma4irqenable, 0x3},
	{"dma4next_high", "DMA 1 Next Descriptor Address (MSB 32)", (const aja_register_t *)&ajareg_dma4next_high, (const aja_regoption_t *)&regopt_dma4next_high, 0x3},
	{"downconvmode", "Downconversion Mode", (const aja_register_t *)&ajareg_downconvmode, (const aja_regoption_t *)&regopt_downconvmode, 0x7},
	{"eaud1c12", "Embedded Audio Group 1 - Ch 1/2 Present", (const aja_register_t *)&ajareg_eaud1c12, (const aja_regoption_t *)&regopt_eaud1c12, 0x1},
	{"eaud1c34", "Embedded Audio Group 1 - Ch 3/4 Present", (const aja_register_t *)&ajareg_eaud1c34, (const aja_regoption_t *)&regopt_eaud1c34, 0x1},
	{"eaud1supress", "Output 1 Embedded Audio Supress", (const aja_register_t *)&ajareg_eaud1supress, (const aja_regoption_t *)&regopt_eaud1supress, 0x7},
	{"eaud2c12", "Embedded Audio Group 2 - Ch 1/2 Present", (const aja_register_t *)&ajareg_eaud2c12, (const aja_regoption_t *)&regopt_eaud2c12, 0x1},
	{"eaud2c34", "Embedded Audio Group 2 - Ch 3/4 Present", (const aja_register_t *)&ajareg_eaud2c34, (const aja_regoption_t *)&regopt_eaud2c34, 0x1},
	{"eaud2supress", "Output 2 Embedded Audio Supress", (const aja_register_t *)&ajareg_eaud2supress, (const aja_regoption_t *)&regopt_eaud2supress, 0x7},
	{"eaud3c12", "Embedded Audio Group 3 - Ch 1/2 Present", (const aja_register_t *)&ajareg_eaud3c12, (const aja_regoption_t *)&regopt_eaud3c12, 0x1},
	{"eaud3c34", "Embedded Audio Group 3 - Ch 3/4 Present", (const aja_register_t *)&ajareg_eaud3c34, (const aja_regoption_t *)&regopt_eaud3c34, 0x1},
	{"eaud4c12", "Embedded Audio Group 4 - Ch 1/2 Present", (const aja_register_t *)&ajareg_eaud4c12, (const aja_regoption_t *)&regopt_eaud4c12, 0x1},
	{"eaud4c34", "Embedded Audio Group 4 - Ch 3/4 Present", (const aja_register_t *)&ajareg_eaud4c34, (const aja_regoption_t *)&regopt_eaud4c34, 0x1},
	{"eaudselect", "Embedded Audio Input Select", (const aja_register_t *)&ajareg_eaudselect, (const aja_regoption_t *)&regopt_eaudselect, 0x7},
	{"eaudsup", "Embedded Audio Supported", (const aja_register_t *)&ajareg_eaudsup, (const aja_regoption_t *)&regopt_eaudsup, 0x1},
	{"firmwarerev", "Firmware Revision Number", (const aja_register_t *)&ajareg_firmwarerev, (const aja_regoption_t *)&regopt_firmwarerev, 0x1},
	{"force64bit", "Force card to use 64bit PCI", (const aja_register_t *)&ajareg_force64bit, (const aja_regoption_t *)&regopt_force64bit, 0x3},
	{"fpgaversion", "FPGA Version Number", (const aja_register_t *)&ajareg_fpgaversion, (const aja_regoption_t *)&regopt_fpgaversion, 0x1},
	{"framegeo", "Frame Geometry", (const aja_register_t *)&ajareg_framegeo, (const aja_regoption_t *)&regopt_framegeo, 0x7},
	{"framerate", "Frame Rate", (const aja_register_t *)&ajareg_framerate, (const aja_regoption_t *)&regopt_framerate, 0x7},
	{"framerate2k", "Extra bit for 2k framerates", (const aja_register_t *)&ajareg_framerate2k, (const aja_regoption_t *)&regopt_framerate2k, 0x7},
	{"horiztiming", "Horizontal Timing", (const aja_register_t *)&ajareg_horiztiming, (const aja_regoption_t *)&regopt_horiztiming, 0x7},
	{"inconvstd", "Input Converter Standard", (const aja_register_t *)&ajareg_inconvstd, (const aja_regoption_t *)&regopt_inconvstd, 0x7},
	{"input1autotime", "Input 1 Autotime", (const aja_register_t *)&ajareg_input1autotime, (const aja_regoption_t *)&regopt_input1autotime, 0x1},
	{"input1extframerate", "Input 1 Extended Frame Rate", (const aja_register_t *)&ajareg_input1extframerate, (const aja_regoption_t *)&regopt_input1extframerate, 0x1},
	{"input1extgeo", "Input 1 Extended Geometry", (const aja_register_t *)&ajareg_input1extgeo, (const aja_regoption_t *)&regopt_input1extgeo, 0x1},
	{"input1field", "Input 1 Field", (const aja_register_t *)&ajareg_input1field, (const aja_regoption_t *)&regopt_input1field, 0x1},
	{"input1format", "Input 1 Format", (const aja_register_t *)&ajareg_input1format, (const aja_regoption_t *)&regopt_input1format, 0x1},
	{"input1framerate", "Input 1 Frame Rate", (const aja_register_t *)&ajareg_input1framerate, (const aja_regoption_t *)&regopt_input1framerate, 0x1},
	{"input1irq", "Input 1 IRQ Active", (const aja_register_t *)&ajareg_input1irq, (const aja_regoption_t *)&regopt_input1irq, 0x1},
	{"input1irqclear", "Input 1 IRQ Clear", (const aja_register_t *)&ajareg_input1irqclear, (const aja_regoption_t *)&regopt_input1irqclear, 0x2},
	{"input1irqenable", "Input1 IRQ Enable", (const aja_register_t *)&ajareg_input1irqenable, (const aja_regoption_t *)&regopt_input1irqenable, 0x3},
	{"input1prog", "Input 1 Progressive Flag", (const aja_register_t *)&ajareg_input1prog, (const aja_regoption_t *)&regopt_input1prog, 0x1},
	{"input1vblank", "Input 1 Vertical Blank Active", (const aja_register_t *)&ajareg_input1vblank, (const aja_regoption_t *)&regopt_input1vblank, 0x1},
	{"input2autotime", "Input 2 Autotime", (const aja_register_t *)&ajareg_input2autotime, (const aja_regoption_t *)&regopt_input2autotime, 0x1},
	{"input2extframerate", "Input 2 Extended Frame Rave", (const aja_register_t *)&ajareg_input2extframerate, (const aja_regoption_t *)&regopt_input2extframerate, 0x1},
	{"input2extgeo", "Input 2 Extended Frame Geometry", (const aja_register_t *)&ajareg_input2extgeo, (const aja_regoption_t *)&regopt_input2extgeo, 0x1},
	{"input2field", "Input 2 Field", (const aja_register_t *)&ajareg_input2field, (const aja_regoption_t *)&regopt_input2field, 0x1},
	{"input2format", "Input 2 Format", (const aja_register_t *)&ajareg_input2format, (const aja_regoption_t *)&regopt_input2format, 0x1},
	{"input2framerate", "Input 2 Frame Rate", (const aja_register_t *)&ajareg_input2framerate, (const aja_regoption_t *)&regopt_input2framerate, 0x1},
	{"input2irq", "Input 2 IRQ Active", (const aja_register_t *)&ajareg_input2irq, (const aja_regoption_t *)&regopt_input2irq, 0x1},
	{"input2irqclear", "Input 2 IRQ Clear", (const aja_register_t *)&ajareg_input2irqclear, (const aja_regoption_t *)&regopt_input2irqclear, 0x2},
	{"input2irqenable", "Input2 IRQ Enable", (const aja_register_t *)&ajareg_input2irqenable, (const aja_regoption_t *)&regopt_input2irqenable, 0x3},
	{"input2prog", "Input 2 Progressive Flag", (const aja_register_t *)&ajareg_input2prog, (const aja_regoption_t *)&regopt_input2prog, 0x1},
	{"input2vblank", "Input 2 Vertical Blank Active", (const aja_register_t *)&ajareg_input2vblank, (const aja_regoption_t *)&regopt_input2vblank, 0x1},
	{"kboxinput", "KBOX Input Selection", (const aja_register_t *)&ajareg_kboxinput, (const aja_regoption_t *)&regopt_kboxinput, 0x7},
	{"kboxmonitor", "KBOX Audio Monitor Output", (const aja_register_t *)&ajareg_kboxmonitor, (const aja_regoption_t *)&regopt_kboxmonitor, 0x7},
	{"leds", "Card LEDs", (const aja_register_t *)&ajareg_leds, (const aja_regoption_t *)&regopt_leds, 0x3},
	{"lut1xpt", "LUT 1 Crosspoint", (const aja_register_t *)&ajareg_lut1xpt, (const aja_regoption_t *)&regopt_lut1xpt, 0x7},
	{"lut2xpt", "LUT 2 Crosspoint", (const aja_register_t *)&ajareg_lut2xpt, (const aja_regoption_t *)&regopt_lut2xpt, 0x7},
	{"mattecb", "Matte Cb Value", (const aja_register_t *)&ajareg_mattecb, (const aja_regoption_t *)&regopt_mattecb, 0x7},
	{"mattecr", "Matte Cr Value", (const aja_register_t *)&ajareg_mattecr, (const aja_regoption_t *)&regopt_mattecr, 0x7},
	{"mattey", "Matte Y Value", (const aja_register_t *)&ajareg_mattey, (const aja_regoption_t *)&regopt_mattey, 0x7},
	{"mixbgkeyxpt", "Mixer Background Key Crosspoint", (const aja_register_t *)&ajareg_mixbgkeyxpt, (const aja_regoption_t *)&regopt_mixbgkeyxpt, 0x7},
	{"mixbgvidxpt", "Mixer Background Video Crosspoint", (const aja_register_t *)&ajareg_mixbgvidxpt, (const aja_regoption_t *)&regopt_mixbgvidxpt, 0x7},
	{"mixer", "Mixer Value", (const aja_register_t *)&ajareg_mixer, (const aja_regoption_t *)&regopt_mixer, 0x7},
	{"mixfgkeyxpt", "Mixer Foreground Key Crosspoint", (const aja_register_t *)&ajareg_mixfgkeyxpt, (const aja_regoption_t *)&regopt_mixfgkeyxpt, 0x7},
	{"mixfgvidxpt", "Mixer Foreground Video Crosspoint", (const aja_register_t *)&ajareg_mixfgvidxpt, (const aja_regoption_t *)&regopt_mixfgvidxpt, 0x7},
	{"outconvstd", "Output Converter Standard", (const aja_register_t *)&ajareg_outconvstd, (const aja_regoption_t *)&regopt_outconvstd, 0x7},
	{"outputfield", "Output Field", (const aja_register_t *)&ajareg_outputfield, (const aja_regoption_t *)&regopt_outputfield, 0x1},
	{"outputirq", "Output Active", (const aja_register_t *)&ajareg_outputirq, (const aja_regoption_t *)&regopt_outputirq, 0x1},
	{"outputirqclear", "Output IRQ Clear", (const aja_register_t *)&ajareg_outputirqclear, (const aja_regoption_t *)&regopt_outputirqclear, 0x2},
	{"outputirqenable", "Output IRQ Enable", (const aja_register_t *)&ajareg_outputirqenable, (const aja_regoption_t *)&regopt_outputirqenable, 0x3},
	{"outputline", "Output Line Number", (const aja_register_t *)&ajareg_outputline, (const aja_regoption_t *)&regopt_outputline, 0x1},
	{"outputvblank", "Output Vertical Blank Active", (const aja_register_t *)&ajareg_outputvblank, (const aja_regoption_t *)&regopt_outputvblank, 0x1},
	{"panhoriz", "Pan Horizontal Offset", (const aja_register_t *)&ajareg_panhoriz, (const aja_regoption_t *)&regopt_panhoriz, 0x7},
	{"panvert", "Pan Vertical Offset", (const aja_register_t *)&ajareg_panvert, (const aja_regoption_t *)&regopt_panvert, 0x7},
	{"panwindow", "Pan window size", (const aja_register_t *)&ajareg_panwindow, (const aja_regoption_t *)&regopt_panwindow, 0x7},
	{"refformat", "Reference Format", (const aja_register_t *)&ajareg_refformat, (const aja_regoption_t *)&regopt_refformat, 0x1},
	{"refframerate", "Reference Frame Rate", (const aja_register_t *)&ajareg_refframerate, (const aja_regoption_t *)&regopt_refframerate, 0x1},
	{"refprog", "Reference Progressive Flag", (const aja_register_t *)&ajareg_refprog, (const aja_regoption_t *)&regopt_refprog, 0x1},
	{"refsource", "Reference Source", (const aja_register_t *)&ajareg_refsource, (const aja_regoption_t *)&regopt_refsource, 0x7},
	{"refvoltage", "Reference Voltage", (const aja_register_t *)&ajareg_refvoltage, (const aja_regoption_t *)&regopt_refvoltage, 0x7},
	{"regclocking", "Register Clocking", (const aja_register_t *)&ajareg_regclocking, (const aja_regoption_t *)&regopt_regclocking, 0x7},
	{"resconv23", "Resolution converter add 2:3", (const aja_register_t *)&ajareg_resconv23, (const aja_regoption_t *)&regopt_resconv23, 0x7},
	{"resconvsdanim", "SD Anamorphic Conversion Mode", (const aja_register_t *)&ajareg_resconvsdanim, (const aja_regoption_t *)&regopt_resconvsdanim, 0x7},
	{"resconvxpt", "Up/Down Converter Crosspoint", (const aja_register_t *)&ajareg_resconvxpt, (const aja_regoption_t *)&regopt_resconvxpt, 0x7},
	{"sdi1out2kline", "SDI 1 Output 2048x1080 mode", (const aja_register_t *)&ajareg_sdi1out2kline, (const aja_regoption_t *)&regopt_sdi1out2kline, 0x7},
	{"sdi1outhblankrgb", "SDI 1 Output HBlank RGB range", (const aja_register_t *)&ajareg_sdi1outhblankrgb, (const aja_regoption_t *)&regopt_sdi1outhblankrgb, 0x7},
	{"sdi1outstd", "SDI 1 Output Standard", (const aja_register_t *)&ajareg_sdi1outstd, (const aja_regoption_t *)&regopt_sdi1outstd, 0x7},
	{"sdi1outxpt", "SDI 1 Output Crosspoint", (const aja_register_t *)&ajareg_sdi1outxpt, (const aja_regoption_t *)&regopt_sdi1outxpt, 0x7},
	{"sdi2out2kline", "SDI 2 Output 2048x1080 mode", (const aja_register_t *)&ajareg_sdi2out2kline, (const aja_regoption_t *)&regopt_sdi2out2kline, 0x7},
	{"sdi2outhblankrgb", "SDI 2 Output HBlank RGB range", (const aja_register_t *)&ajareg_sdi2outhblankrgb, (const aja_regoption_t *)&regopt_sdi2outhblankrgb, 0x7},
	{"sdi2outstd", "SDI 2 Output Standard", (const aja_register_t *)&ajareg_sdi2outstd, (const aja_regoption_t *)&regopt_sdi2outstd, 0x7},
	{"sdi2outxpt", "SDI 2 Output Crosspoint", (const aja_register_t *)&ajareg_sdi2outxpt, (const aja_regoption_t *)&regopt_sdi2outxpt, 0x7},
	{"serialhigh", "Board Serial High", (const aja_register_t *)&ajareg_serialhigh, (const aja_regoption_t *)&regopt_serialhigh, 0x1},
	{"seriallow", "Board Serial Low", (const aja_register_t *)&ajareg_seriallow, (const aja_regoption_t *)&regopt_seriallow, 0x1},
	{"splitslope", "Split Screen Slope", (const aja_register_t *)&ajareg_splitslope, (const aja_regoption_t *)&regopt_splitslope, 0x7},
	{"splitstart", "Split Screen Start", (const aja_register_t *)&ajareg_splitstart, (const aja_regoption_t *)&regopt_splitstart, 0x7},
	{"splittype", "Split Screen Type", (const aja_register_t *)&ajareg_splittype, (const aja_regoption_t *)&regopt_splittype, 0x7},
	{"standard", "Video Standard", (const aja_register_t *)&ajareg_standard, (const aja_regoption_t *)&regopt_standard, 0x7},
	{"strapenabled", "Strap Resistor Enabled", (const aja_register_t *)&ajareg_strapenabled, (const aja_regoption_t *)&regopt_strapenabled, 0x3},
	{"uartenablerx", "UART recieve enable", (const aja_register_t *)&ajareg_uartenablerx, (const aja_regoption_t *)&regopt_uartenablerx, 0x3},
	{"uartenabletx", "UART transmit enable", (const aja_register_t *)&ajareg_uartenabletx, (const aja_regoption_t *)&regopt_uartenabletx, 0x3},
	{"uartin", "UART recieve data", (const aja_register_t *)&ajareg_uartin, (const aja_regoption_t *)&regopt_uartin, 0x1},
	{"uartout", "UART transmit data", (const aja_register_t *)&ajareg_uartout, (const aja_regoption_t *)&regopt_uartout, 0x2},
	{"uartrxirq", "UART Rx IRQ Active", (const aja_register_t *)&ajareg_uartrxirq, (const aja_regoption_t *)&regopt_uartrxirq, 0x1},
	{"uartrxirqclear", "UART Rx IRQ Clear", (const aja_register_t *)&ajareg_uartrxirqclear, (const aja_regoption_t *)&regopt_uartrxirqclear, 0x2},
	{"uartrxirqenable", "UART Rx IRQ Enable", (const aja_register_t *)&ajareg_uartrxirqenable, (const aja_regoption_t *)&regopt_uartrxirqenable, 0x3},
	{"uartrxoverrun", "UART rx fifo overrun", (const aja_register_t *)&ajareg_uartrxoverrun, (const aja_regoption_t *)&regopt_uartrxoverrun, 0x3},
	{"uartrxparityerror", "UART rx parity error", (const aja_register_t *)&ajareg_uartrxparityerror, (const aja_regoption_t *)&regopt_uartrxparityerror, 0x3},
	{"uartstatusrx", "UART recieve status", (const aja_register_t *)&ajareg_uartstatusrx, (const aja_regoption_t *)&regopt_uartstatusrx, 0x3},
	{"uartstatustx", "UART transmit fifo status", (const aja_register_t *)&ajareg_uartstatustx, (const aja_regoption_t *)&regopt_uartstatustx, 0x1},
	{"uarttxirq", "UART Tx IRQ Active", (const aja_register_t *)&ajareg_uarttxirq, (const aja_regoption_t *)&regopt_uarttxirq, 0x1},
	{"uarttxirqclear", "UART Tx IRQ Clear", (const aja_register_t *)&ajareg_uarttxirqclear, (const aja_regoption_t *)&regopt_uarttxirqclear, 0x2},
	{"uarttxirqenable", "UART Tx IRQ Enable", (const aja_register_t *)&ajareg_uarttxirqenable, (const aja_regoption_t *)&regopt_uarttxirqenable, 0x3},
	{"upconvmode", "Upconversion Mode", (const aja_register_t *)&ajareg_upconvmode, (const aja_regoption_t *)&regopt_upconvmode, 0x7},
	{"verttiming", "Vertical Timing", (const aja_register_t *)&ajareg_verttiming, (const aja_regoption_t *)&regopt_verttiming, 0x7},
	{"vidfw_data", "Video Firmware Data", (const aja_register_t *)&ajareg_vidfw_data, (const aja_regoption_t *)&regopt_vidfw_data, 0x2},
	{"vidfw_done", "Video Firmware Done", (const aja_register_t *)&ajareg_vidfw_done, (const aja_regoption_t *)&regopt_vidfw_done, 0x1},
	{"vidfw_pcix", "Video Firmware Programming PCI-X programming mode", (const aja_register_t *)&ajareg_vidfw_pcix, (const aja_regoption_t *)&regopt_vidfw_pcix, 0x3},
	{"vidfw_program", "Video Firmware Program", (const aja_register_t *)&ajareg_vidfw_program, (const aja_regoption_t *)&regopt_vidfw_program, 0x2},
	{"vidfw_ready", "Video Firmware Ready", (const aja_register_t *)&ajareg_vidfw_ready, (const aja_regoption_t *)&regopt_vidfw_ready, 0x1},
	{"vidfw_reset", "Video Firmware Reset", (const aja_register_t *)&ajareg_vidfw_reset, (const aja_regoption_t *)&regopt_vidfw_reset, 0x2},
	{"viv", "Virtex Interrupt Validation", (const aja_register_t *)&ajareg_viv, (const aja_regoption_t *)&regopt_viv, 0x1},
	{"vpc_bgcont", "Video Processing Control - Background Control", (const aja_register_t *)&ajareg_vpc_bgcont, (const aja_regoption_t *)&regopt_vpc_bgcont, 0x7},
	{"vpc_fgcont", "Video Processing Control - Foreground Control", (const aja_register_t *)&ajareg_vpc_fgcont, (const aja_regoption_t *)&regopt_vpc_fgcont, 0x7},
	{"vpc_limiting", "Video Processing Control - Limiting", (const aja_register_t *)&ajareg_vpc_limiting, (const aja_regoption_t *)&regopt_vpc_limiting, 0x7},
	{"vpc_mode", "Video Processing Control - Mode", (const aja_register_t *)&ajareg_vpc_mode, (const aja_regoption_t *)&regopt_vpc_mode, 0x7},
	{"vpc_mux1", "Video Processing Control - Mux1", (const aja_register_t *)&ajareg_vpc_mux1, (const aja_regoption_t *)&regopt_vpc_mux1, 0x7},
	{"vpc_mux2", "Video Processing Control - Mux2", (const aja_register_t *)&ajareg_vpc_mux2, (const aja_regoption_t *)&regopt_vpc_mux2, 0x7},
	{"vpc_mux3", "Video Processint Control - Mux3", (const aja_register_t *)&ajareg_vpc_mux3, (const aja_regoption_t *)&regopt_vpc_mux3, 0x7},
	{"vpc_mux4", "Video Processing Control - Mux4", (const aja_register_t *)&ajareg_vpc_mux4, (const aja_regoption_t *)&regopt_vpc_mux4, 0x7},
	{"vpc_mux5", "Video Processing Control - Mux5", (const aja_register_t *)&ajareg_vpc_mux5, (const aja_regoption_t *)&regopt_vpc_mux5, 0x7},
	{"vpc_standard", "Video Processing Control - Standard", (const aja_register_t *)&ajareg_vpc_standard, (const aja_regoption_t *)&regopt_vpc_standard, 0x7},
	{"vpc_syncfail", "Video Processing Control - Sync Fail", (const aja_register_t *)&ajareg_vpc_syncfail, (const aja_regoption_t *)&regopt_vpc_syncfail, 0x1},
	{"vpcc_bgkey", "Video Processing Crosspoint - Background Key", (const aja_register_t *)&ajareg_vpcc_bgkey, (const aja_regoption_t *)&regopt_vpcc_bgkey, 0x7},
	{"vpcc_bgv", "Video Processing Crosspoint - Background Video", (const aja_register_t *)&ajareg_vpcc_bgv, (const aja_regoption_t *)&regopt_vpcc_bgv, 0x7},
	{"vpcc_fgkey", "Video Processing Crosspoint - Foreground Key", (const aja_register_t *)&ajareg_vpcc_fgkey, (const aja_regoption_t *)&regopt_vpcc_fgkey, 0x7},
	{"vpcc_fgv", "Video Processing Crosspoint - Foreground Video", (const aja_register_t *)&ajareg_vpcc_fgv, (const aja_regoption_t *)&regopt_vpcc_fgv, 0x7},
	{"vpcc_secv", "Video Processing Crosspoint - Secondary Video", (const aja_register_t *)&ajareg_vpcc_secv, (const aja_regoption_t *)&regopt_vpcc_secv, 0x7},
	{NULL, NULL, NULL, NULL, 0}
};


#endif /* _AJA_REGSTRINGS_H_ defined */

